name: OAuth2Client
version: ${project.version}
main: cz.bloodbear.OAuth2Client.paper.OAuth2Client
api-version: 1.20

author: Mtn16, warix8
description: Seamless OAuth2 Integration for Velocity and Paper
website: https://github.com/aeecleclair/minecraft-proxy-link-oauth2-plugin
depend: [LuckPerms]
softdepend: [PlaceholderAPI, Plan]

permissions:
  oauth2client.player:
    default: notop
    children:
      oauth2client.player.link: true
      oauth2client.player.unlink: true
      oauth2client.player.info: true

  oauth2client.admin:
    default: op
    children:
      oauth2client.admin.reload: true
      oauth2client.admin.resync: true
      oauth2client.admin.resyncall: true
